set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P17 [get_ports clk]












set_property IOSTANDARD LVCMOS33 [get_ports {light[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property PACKAGE_PIN R15 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN R1 [get_ports rst_n]
set_property PACKAGE_PIN T1 [get_ports s]
set_property PACKAGE_PIN H17 [get_ports speaker]
set_property PACKAGE_PIN F6 [get_ports {light[6]}]
set_property PACKAGE_PIN G4 [get_ports {light[5]}]
set_property PACKAGE_PIN G3 [get_ports {light[4]}]
set_property PACKAGE_PIN J4 [get_ports {light[3]}]
set_property PACKAGE_PIN H4 [get_ports {light[2]}]
set_property PACKAGE_PIN J3 [get_ports {light[1]}]
set_property PACKAGE_PIN J2 [get_ports {light[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[0]}]
set_property PACKAGE_PIN B4 [get_ports {seg_out[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN G2 [get_ports {segs[3]}]
set_property PACKAGE_PIN C2 [get_ports {segs[2]}]
set_property PACKAGE_PIN C1 [get_ports {segs[1]}]
set_property PACKAGE_PIN H1 [get_ports {segs[0]}]
set_property PACKAGE_PIN U4 [get_ports key1]
set_property PACKAGE_PIN R17 [get_ports key2]
set_property PACKAGE_PIN R1 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports key1]
set_property IOSTANDARD LVCMOS33 [get_ports key2]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN D7 [get_ports hsync]
set_property PACKAGE_PIN C4 [get_ports vsync]
set_property PACKAGE_PIN P17 [get_ports sys_clk]
set_property PACKAGE_PIN R1 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[0]}]
set_property PACKAGE_PIN D15 [get_ports {rgb[15]}]
set_property PACKAGE_PIN D14 [get_ports {rgb[14]}]
set_property PACKAGE_PIN D13 [get_ports {rgb[13]}]
set_property PACKAGE_PIN D12 [get_ports {rgb[12]}]
set_property PACKAGE_PIN A8 [get_ports {rgb[10]}]
set_property PACKAGE_PIN B8 [get_ports {rgb[9]}]
set_property PACKAGE_PIN A9 [get_ports {rgb[8]}]
set_property PACKAGE_PIN B9 [get_ports {rgb[7]}]
set_property PACKAGE_PIN A10 [get_ports {rgb[6]}]
set_property PACKAGE_PIN A5 [get_ports {rgb[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[0]}]
set_property PACKAGE_PIN F5 [get_ports {vga_rgb[11]}]
set_property PACKAGE_PIN C6 [get_ports {vga_rgb[10]}]
set_property PACKAGE_PIN C5 [get_ports {vga_rgb[9]}]
set_property PACKAGE_PIN B7 [get_ports {vga_rgb[8]}]
set_property PACKAGE_PIN B6 [get_ports {vga_rgb[7]}]
set_property PACKAGE_PIN A6 [get_ports {vga_rgb[6]}]
set_property PACKAGE_PIN A5 [get_ports {vga_rgb[5]}]
set_property PACKAGE_PIN D8 [get_ports {vga_rgb[4]}]
set_property PACKAGE_PIN C7 [get_ports {vga_rgb[3]}]
set_property PACKAGE_PIN E6 [get_ports {vga_rgb[2]}]
set_property PACKAGE_PIN E5 [get_ports {vga_rgb[1]}]
set_property PACKAGE_PIN E7 [get_ports {vga_rgb[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property PACKAGE_PIN P17 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property PACKAGE_PIN E7 [get_ports {blue[3]}]
set_property PACKAGE_PIN E5 [get_ports {blue[2]}]
set_property PACKAGE_PIN E6 [get_ports {blue[1]}]
set_property PACKAGE_PIN C7 [get_ports {blue[0]}]
set_property PACKAGE_PIN D8 [get_ports {green[3]}]
set_property PACKAGE_PIN A5 [get_ports {green[2]}]
set_property PACKAGE_PIN A6 [get_ports {green[1]}]
set_property PACKAGE_PIN B6 [get_ports {green[0]}]
set_property PACKAGE_PIN B7 [get_ports {red[3]}]
set_property PACKAGE_PIN C5 [get_ports {red[2]}]
set_property PACKAGE_PIN C6 [get_ports {red[1]}]
set_property PACKAGE_PIN F5 [get_ports {red[0]}]
