# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# IP: d:/Digital Logic/git/IP/dcm_25m/dcm_25m.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dcm_25m || ORIG_REF_NAME==dcm_25m} -quiet] -quiet
