# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/final-piano/piano/piano.cache/wt [current_project]
set_property parent.project_path D:/final-piano/piano/piano.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/final-piano/piano/piano.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{D:/final-piano/piano/piano.srcs/sources_1/imports/Digital Logic/WORK/piano/mode4.coe}}
add_files D:/final-piano/piano/mode_1.coe
add_files D:/final-piano/piano/mode_2.coe
add_files D:/final-piano/piano/mode_3.coe
add_files d:/final-piano/piano/CrazyBird.coe
read_verilog -library xil_defaultlib {
  D:/final-piano/piano/piano.srcs/sources_1/new/AutoPlayMode.v
  D:/final-piano/piano/piano.srcs/sources_1/imports/new/FreeMode.v
  D:/final-piano/piano/piano.srcs/sources_1/new/HappyBirthday.v
  D:/final-piano/piano/piano.srcs/sources_1/new/LearnMode.v
  D:/final-piano/piano/piano.srcs/sources_1/imports/new/LittleStar.v
  D:/final-piano/piano/piano.srcs/sources_1/new/MusicRecorder.v
  D:/final-piano/piano/piano.srcs/sources_1/imports/new/Spring.v
  D:/final-piano/piano/piano.srcs/sources_1/new/VGAcontroller.v
  D:/final-piano/piano/piano.srcs/sources_1/new/debounce_button.v
  D:/final-piano/piano/piano.srcs/sources_1/new/divclk_20ms.v
  D:/final-piano/piano/piano.srcs/sources_1/new/littlestar_learning.v
  D:/final-piano/piano/piano.srcs/sources_1/new/scan_seg.v
  D:/final-piano/piano/piano.srcs/sources_1/imports/new/seven_seg_tube.v
  D:/final-piano/piano/piano.srcs/sources_1/new/MiniPiano.v
}
read_ip -quiet D:/final-piano/piano/piano.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
set_property used_in_implementation false [get_files -all d:/final-piano/piano/piano.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc]
set_property used_in_implementation false [get_files -all d:/final-piano/piano/piano.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc]
set_property used_in_implementation false [get_files -all d:/final-piano/piano/piano.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc]

read_ip -quiet D:/final-piano/piano/piano.srcs/sources_1/ip/pic/pic.xci
set_property used_in_implementation false [get_files -all d:/final-piano/piano/piano.srcs/sources_1/ip/pic/pic_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/final-piano/piano/piano.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files D:/final-piano/piano/piano.srcs/constrs_1/new/constraint.xdc]


synth_design -top MiniPiano -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MiniPiano.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MiniPiano_utilization_synth.rpt -pb MiniPiano_utilization_synth.pb"
